version: "3.9"

services:
  
  api:
    build:
      context: ./container_data
      dockerfile: Dockerfile
    container_name: "rs-api"
    restart: unless-stopped
    volumes:
      - "./container_data:/usr/src/app"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.rs-api.rule=Host(`rs-api.extacy.cc`)"
      - "traefik.http.routers.rs-api.entrypoints=websecure"
      - "traefik.http.routers.rs-api.tls.certresolver=dnsresolver"
      - "traefik.http.services.rs-api.loadbalancer.server.port=3000"
    networks:
      - traefik
      - realmsense

networks:
  traefik:
    external: true
  realmsense:
    external: true
